anjoy8/Blog.Core

- Blog.Core.FrameWork/DbHelper.ttinclude
> and prop.class_desc='OBJECT_OR_COLUMN'

- Blog.Core.Common/LogHelper/LogLock.cs
fixed LogLock.cs for Linux Path Compatibility
> fixed LogLock.cs for Linux Path Compatibility

- Blog.Core.Common/Hubs/ChatHub.cs
- Blog.Core.Common/Hubs/IChatClient.cs
- Blog.Core.Common/LogHelper/LogLock.cs
- Blog.Core/Middlewares/RequRespLogMildd.cs
- Blog.Core/Program.cs
- Blog.Core/appsettings.json
AllowSynchronousIO  & Add IChatClient for SignalR HUB
> AllowSynchronousIO  & Add IChatClient for SignalR HUB

- Blog.Core.Services/BASE/BaseServices.cs
- Blog.Core/AOP/CacheAOPbase.cs
> 修复缓存键值计算表达树错误问题

- Blog.Core/AOP/BlogRedisCacheAOP.cs
> 代码已经提交测试 pr操作

- Blog.Core.Services/BlogArticleServices.cs
> 优化services层获取博客上一篇下一篇逻辑

- Blog.Core.Extensions/Middlewares/QuartzJobMildd.cs
- Blog.Core.Tasks/QuartzNet/SchedulerCenterServer.cs
修复 计划任务 在程序启动时处理不存在的类的时候导致程序异常
> 修复 计划任务 在程序启动时处理不存在的类的时候导致程序异常

- Blog.Core.Api/Controllers/DbFirst/DbFirstController.cs
- Blog.Core.Model/Seed/FrameSeed.cs
优化Controller生成代码 首字母大写
新增根据数据库连接+数据库表名生成包含model层在内的所有的框架文件。
> 优化Controller生成代码 首字母大写  新增根据数据库连接+数据库表名生成包含model层在内的所有的框架文件。

- Blog.Core.Api/Controllers/ValuesController.cs
- Blog.Core.IServices/BASE/IBaseServices.cs
- Blog.Core.Repository/BASE/BaseRepository.cs
- Blog.Core.Repository/BASE/IBaseRepository.cs
- Blog.Core.Services/BASE/BaseServices.cs
Modify query data list according to 
specific column, 
modify filter condition (original string) to expression, 
which can be used for multiple filter conditions
修改按照特定列查询数据列表，修改过滤条件（原string）修改为表达式，可用于多过滤条件
> Modify query data list according to  specific column to expression修改按照特定列查询数据列表，修改过滤条件（原string）修改为表达式，可用于多过滤条件

- Blog.Core.Common/MemoryCache/ICachingProvider.cs
- Blog.Core.Common/MemoryCache/MemoryCaching.cs
- Blog.Core.Extensions/AOP/BlogCacheAOP.cs
Memory Cach Expiration Time Setting内存缓存过期时间设置
> Memory Cach Expiration Time Setting内存缓存过期时间设置

- Blog.Core.Api/Blog.Core.xml
- Blog.Core.Api/Controllers/TasksQzController.cs
- Blog.Core.Tasks/QuartzNet/ISchedulerCenter.cs
- Blog.Core.Tasks/QuartzNet/SchedulerCenterServer.cs
> 添加 任务 立即执行 的功能

- Blog.Core.Api/Controllers/BaseApiCpntroller.cs
- Blog.Core.Api/Controllers/BlogController.cs
- Blog.Core.Api/Controllers/LoginController.cs
- Blog.Core.Model/MessageModel.cs
参照模仿公司魔改版，加了个Base控制器，封装了常用的返回，添加了无泛型的 MessageModel
（blog控制器的返回参数全改了，login控制器的返回改了一部分，其余暂时没动）
主要目的为了减少代码控制器层代码量
还想着Base控制器放快速获取token信息的方法..怕出问题，先看能不能过了这个先
> 控制器层封装了一些东西

- Blog.Core.Api/Blog.Core.xml
- Blog.Core.Api/Controllers/ValuesController.cs
- Blog.Core.Api/Program.cs
- Blog.Core.Api/appsettings.apollo.json
- Blog.Core.Extensions/Apollo/ApolloOptions.cs
- Blog.Core.Extensions/Apollo/ConfigurationBuilderExtensions.cs
- Blog.Core.Extensions/Blog.Core.Extensions.csproj
接入Apollo配置中心（暂未实现特定操作的更改(如中间件的信息的更改)后续会继续完善）
> Added Apollo configuration center

- Blog.Core.Api/Startup.cs
- Blog.Core.Api/appsettings.json
- Blog.Core.EventBus/Blog.Core.EventBus.csproj
- Blog.Core.EventBus/EventBusKafka/EventBusKafka.cs
- Blog.Core.EventBus/EventBusKafka/IKafkaConnectionPool.cs
- Blog.Core.EventBus/EventBusKafka/KafkaConnectionPool.cs
- Blog.Core.EventBus/EventBusKafka/KafkaConsumerHostService.cs
- Blog.Core.EventBus/EventBusKafka/KafkaOptions.cs
- Blog.Core.EventBus/EventBusKafka/ProtobufTransfer.cs
- Blog.Core.Extensions/ServiceExtensions/EventBusSetup.cs
- Blog.Core.Extensions/ServiceExtensions/KafkaSetup.cs
创建了一个新分支：增加基于kafka的消息通信
kafka消息存储展示：
> Kafka message communication

- Blog.Core.Common/LogHelper/Seri/SerilogServer.cs
注释SerilogServer类下WriteLog方法中另三种日志记录方法
> 解决WriteLog方法重复记录4次日志问题

- Blog.Core.Api/Controllers/BaseApiController.cs
- Blog.Core.Api/Controllers/BlogController.cs
- Blog.Core.Api/Controllers/LoginController.cs
- Blog.Core.Api/Controllers/MonitorController.cs
- Blog.Core.Api/Controllers/NacosController.cs
- Blog.Core.Api/Controllers/PermissionController.cs
BaseApiCpntroller => BaseApiController
还有一些类似如下的小修改
```
//return new MessageModel<List<Permission>>()
//{
//    msg = "获取成功",
//    success = true,
//    response = permissions
//};
return Success(permissions, "获取成功");
```
> 修改错误的基控制器名字，修改了权限菜单控制器的一些返回

- Blog.Core.Api/Blog.Core.xml
- Blog.Core.Api/Controllers/BaseApiController.cs
- Blog.Core.Api/Controllers/ModuleController.cs
- Blog.Core.Api/Controllers/MonitorController.cs
- Blog.Core.Api/Controllers/RoleController.cs
- Blog.Core.Api/Controllers/WeChatController.cs
继承BaseApiController控制器，简化接口返回写法，省去多余代码
更改一些简单的流程判断逻辑，不符合条件的直接先返回 if(false) return 而不是 if(true) 再包在里面写逻辑
> 更改部分接口的返回方式，简化返回代码

- Blog.Core.Repository/UnitOfWork/UnitOfWork.cs
> 防止同一范围内，异步执行事务误触非当前线程事务

- Blog.Core.Api/Controllers/BaseApiController.cs
- Blog.Core.Model/PageModel.cs
- Blog.Core.Repository/BASE/BaseRepository.cs
modify pageCount of PageModel, Add ConvertTo used for AutoMapper
> Optimize PageModel

- Blog.Core.Api/Blog.Core.xml
- Blog.Core.Api/Controllers/ValuesController.cs
- Blog.Core.Api/Startup.cs
- Blog.Core.Common/HttpPolly/HttpPollyHelper.cs
- Blog.Core.Common/HttpPolly/IHttpPollyHelper.cs
- Blog.Core.Extensions/Blog.Core.Extensions.csproj
- Blog.Core.Extensions/ServiceExtensions/HttpPollySetup.cs
- Blog.Core.Model/HttpEnum.cs
> Http Polly集成

- Blog.Core.Api/Startup.cs
- Blog.Core.Extensions/Blog.Core.Extensions.csproj
- Blog.Core.Extensions/ServiceExtensions/SwaggerSetup.cs
Enable description of enum in swagger, convert enum to string in Schema.
> Enable description of enum in swagger

- Blog.Core.Api/Blog.Core.Model.xml
- Blog.Core.Api/Controllers/ValuesController.cs
- Blog.Core.Model/ViewModels/EnumDemoDto.cs
> Add enum demo to #254

- Blog.Core.Api/Blog.Core.xml
- Blog.Core.Api/Controllers/ImgController.cs
- Blog.Core.Model/Blog.Core.Model.csproj
- Blog.Core.Model/ViewModels/UploadFileDto.cs
use model binding in InsertPicture, can be test in swagger UI.
> use model binding in InsertPicture

- Blog.Core.Api/Blog.Core.xml
- Blog.Core.Api/Controllers/ImgController.cs
> Using DI in ImgController

- Blog.Core.Repository/MongoRepository/IMongoBaseRepository.cs
- Blog.Core.Repository/MongoRepository/MongoBaseRepository.cs
- Blog.Core.Tests/DependencyInjection/DI_Test.cs
- Blog.Core.Tests/Repository_Test/MongoRepository_Base_Should.cs
MongoRepository
ObjectId，条件查询封装优化
> MongoRepository优化

- Blog.Core.Common/Helper/DynamicLinqFactory.cs
- Blog.Core.Common/Helper/UtilConvert.cs
- Blog.Core.Tests/Common_Test/DynamicLambdaTest.cs
1.使用正则匹配
1.连接符支持 &&、&
2.比较符支持 >、>=、==、=、<、<=、like、contains、in
3.优化处理特殊符号，一般情况都可以应对
4.最好使用“”包括值，数值类型可不用““
单元测试:DynamicLambdaTest
结果
tests (1 test) [0:00.636] Success
Blog.Core.Tests (1 test) [0:00.636] Success
Blog.Core.Tests.Common_Test (1 test) [0:00.636] Success
DynamicLambdaTest (1 test) [0:00.636] Success
Get_Blogs_DynamicTest [0:00.636] Success
[{"bID":1,"bsubmitter":"admin","btitle":"测试数据：IIS new add website ，some wrong:The requested page cannot be accessed because the related configuration data for the page is invalid.","bcategory":"技术博文","bcontent":"                            <p>问题:</p><h1><a href=\"https://www.cnblogs.com/yipeng-yu/p/6210380.html\">The requested page cannot be accessed because the related configuration data for the page is invalid.</a></h1><p>HTTP Error 500.19 - …
> ✨⚡️ 动态Lambda 在兼容原有的操作上优化动态查询条件、处理特殊符号
